apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: monitoring
data:
  blackbox.yml: |
    modules:
      # HTTP probe - basic connectivity check
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200]
          method: GET
          follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: false
          preferred_ip_protocol: "ip4"

      # HTTP probe with SSL verification
      http_2xx_ssl:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200]
          method: GET
          follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: true
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4"

      # HTTP POST probe for API endpoints
      http_post_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200, 201, 204]
          method: POST
          headers:
            Content-Type: application/json
          preferred_ip_protocol: "ip4"

      # Health check probe - expects JSON response
      http_health:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200]
          method: GET
          fail_if_body_not_matches_regexp:
            - '"status":\s*"(healthy|ok|UP)"'
          preferred_ip_protocol: "ip4"

      # TCP probe
      tcp_connect:
        prober: tcp
        timeout: 5s
        tcp:
          preferred_ip_protocol: "ip4"

      # TCP with TLS
      tcp_connect_tls:
        prober: tcp
        timeout: 5s
        tcp:
          preferred_ip_protocol: "ip4"
          tls: true
          tls_config:
            insecure_skip_verify: false

      # DNS probe
      dns_udp:
        prober: dns
        timeout: 5s
        dns:
          query_name: "kubernetes.default.svc.cluster.local"
          query_type: "A"
          valid_rcodes:
            - NOERROR
          preferred_ip_protocol: "ip4"
          transport_protocol: "udp"

      # ICMP ping probe
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: "ip4"

      # gRPC probe
      grpc:
        prober: grpc
        timeout: 5s
        grpc:
          tls: false
          preferred_ip_protocol: "ip4"

      # gRPC with TLS
      grpc_tls:
        prober: grpc
        timeout: 5s
        grpc:
          tls: true
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
        app.kubernetes.io/component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9115"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.24.0
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/blackbox/blackbox.yml
            - --log.level=info
          ports:
            - name: http
              containerPort: 9115
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 9115
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9115
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    app.kubernetes.io/name: blackbox-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-targets
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
data:
  blackbox-targets.yaml: |
    # Prometheus scrape config for blackbox exporter
    # Add this to your prometheus.yml scrape_configs section

    scrape_configs:
      # CRM Services Health Checks
      - job_name: 'blackbox-http-services'
        metrics_path: /probe
        params:
          module: [http_health]
        static_configs:
          - targets:
              - http://iam-service.crm.svc.cluster.local:8081/health
              - http://customer-service.crm.svc.cluster.local:8082/health
              - http://sales-service.crm.svc.cluster.local:8083/health
              - http://notification-service.crm.svc.cluster.local:8084/health
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
          - source_labels: [__param_target]
            regex: 'http://([^.]+)\..*'
            target_label: service
            replacement: '${1}'

      # API Gateway / Ingress Health
      - job_name: 'blackbox-http-ingress'
        metrics_path: /probe
        params:
          module: [http_2xx_ssl]
        static_configs:
          - targets:
              - https://api.crm-platform.local/health
              - https://api.crm-platform.local/api/v1/health
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115

      # Database TCP Connectivity
      - job_name: 'blackbox-tcp-databases'
        metrics_path: /probe
        params:
          module: [tcp_connect]
        static_configs:
          - targets:
              - postgres.crm.svc.cluster.local:5432
              - mongodb.crm.svc.cluster.local:27017
              - redis.crm.svc.cluster.local:6379
              - rabbitmq.crm.svc.cluster.local:5672
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
          - source_labels: [__param_target]
            regex: '([^.]+)\..*'
            target_label: service
            replacement: '${1}'

      # DNS Resolution Check
      - job_name: 'blackbox-dns'
        metrics_path: /probe
        params:
          module: [dns_udp]
        static_configs:
          - targets:
              - kube-dns.kube-system.svc.cluster.local:53
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115

      # gRPC Services (if applicable)
      - job_name: 'blackbox-grpc-services'
        metrics_path: /probe
        params:
          module: [grpc]
        static_configs:
          - targets:
              - iam-service.crm.svc.cluster.local:9081
              - customer-service.crm.svc.cluster.local:9082
              - sales-service.crm.svc.cluster.local:9083
              - notification-service.crm.svc.cluster.local:9084
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
          - source_labels: [__param_target]
            regex: '([^.]+)\..*'
            target_label: service
            replacement: '${1}'
